CREATE OR REPLACE PROCEDURE parse_select(JSON_FILE JSON_OBJECT_T) IS
    RESULT CLOB;
    JSON_OBJECT_ARRAY JSON_ARRAY_T;
    JSON_OBJECT_ARRAY_SIZE NUMBER;
BEGIN
    RESULT := 'SELECT ';

    JSON_OBJECT_ARRAY := JSON_FILE.GET_ARRAY('columns');
    JSON_OBJECT_ARRAY_SIZE := JSON_OBJECT_ARRAY.GET_SIZE() - 1;
    FOR i IN 0..JSON_OBJECT_ARRAY_SIZE LOOP
        RESULT := RESULT || JSON_OBJECT_ARRAY.GET_STRING(i);
        IF i < JSON_OBJECT_ARRAY_SIZE THEN
            RESULT := RESULT || ', ';
        END IF;
    END LOOP;

    RESULT := RESULT || ' FROM ';

    JSON_OBJECT_ARRAY := JSON_FILE.GET_ARRAY('tables');
    JSON_OBJECT_ARRAY_SIZE := JSON_OBJECT_ARRAY.GET_SIZE() - 1;
    FOR i IN 0..JSON_OBJECT_ARRAY_SIZE LOOP
        RESULT := RESULT || JSON_OBJECT_ARRAY.GET_STRING(i);
        IF i < JSON_OBJECT_ARRAY_SIZE THEN
            RESULT := RESULT || ', ';
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(RESULT);
END parse_select;

DECLARE
    JSON_TEXT CLOB;
BEGIN
    JSON_TEXT := '
{
  "type": "SELECT",
  "columns": [''Houses.ADDRESS'', ''Citizens.NAME''],
  "tables": [''Houses'', ''Citizens'']
}
';
    parse_select(JSON_OBJECT_T.PARSE(JSON_TEXT));
END;