DROP TABLE PEOPLE_LOGS;
CREATE TABLE PEOPLE_LOGS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT VARCHAR2(10),
    EVENT_TIME TIMESTAMP,

    PERSON_ID NUMBER,

    OLD_NAME VARCHAR2(100),
    NEW_NAME VARCHAR2(100),

    OLD_DATE_OF_BIRTH TIMESTAMP,
    NEW_DATE_OF_BIRTH TIMESTAMP
);

DROP TABLE LOCATIONS_LOGS;
CREATE TABLE LOCATIONS_LOGS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT VARCHAR2(10),
    EVENT_TIME TIMESTAMP,

    LOCATION_ID NUMBER,

    OLD_ADDRESS VARCHAR2(100),
    NEW_ADDRESS VARCHAR2(100),

    OLD_POST_INDEX NUMBER,
    NEW_POST_INDEX NUMBER
);

CREATE TABLE PASSPORTS_LOGS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT VARCHAR2(10),
    EVENT_TIME TIMESTAMP,

    PASSPORT_ID NUMBER,

    OLD_PERSON_ID NUMBER,
    NEW_PERSON_ID NUMBER,

    OLD_ISSUE_DATE TIMESTAMP,
    NEW_ISSUE_DATE TIMESTAMP,

    OLD_LOCATION_ID NUMBER,
    NEW_LOCATION_ID NUMBER
);
