CREATE TABLE PEOPLE (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    DATE_OF_BIRTH TIMESTAMP
);

CREATE TABLE LOCATIONS (
    ID NUMBER PRIMARY KEY,
    ADDRESS VARCHAR2(100),
    POST_INDEX NUMBER
);

CREATE TABLE PASSPORTS (
    ID NUMBER PRIMARY KEY,
    PERSON_ID NUMBER,
    ISSUE_DATE TIMESTAMP,
    LOCATION_ID NUMBER,
    CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PEOPLE(ID),
    CONSTRAINT FK_LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID)
);


INSERT INTO PEOPLE VALUES (1, 'John Davis', TO_DATE('04-05-1985', 'DD-MM-YYYY'));
INSERT INTO PEOPLE VALUES (2, 'Emma Davis', TO_DATE('25-11-1985', 'DD-MM-YYYY'));
INSERT INTO PEOPLE VALUES (3, 'Sophia Rodriguez', TO_DATE('15-01-1996', 'DD-MM-YYYY'));
INSERT INTO PEOPLE VALUES (4, 'Michael Thompson Jr.', TO_DATE('30-09-1969', 'DD-MM-YYYY'));

INSERT INTO LOCATIONS VALUES (1, '1600 Amphitheatre Parkway, Mountain View', 123321);
INSERT INTO LOCATIONS VALUES (2, '221B Baker Street, San Francisco', 234043);
INSERT INTO LOCATIONS VALUES (3, '1600 Pennsylvania Avenue NW, Washington D.C.', 403346);

INSERT INTO PASSPORTS VALUES (1, 1, TO_DATE('08-10-2016', 'DD-MM-YYYY'), 1);
INSERT INTO PASSPORTS VALUES (2, 2, TO_DATE('28-02-2020', 'DD-MM-YYYY'), 1);
INSERT INTO PASSPORTS VALUES (3, 3, TO_DATE('05-05-2013', 'DD-MM-YYYY'), 2);
INSERT INTO PASSPORTS VALUES (4, 4, TO_DATE('04-05-2018', 'DD-MM-YYYY'), 3);

DELETE FROM PASSPORTS WHERE ID = ID;
DELETE FROM PEOPLE WHERE ID = ID;
DELETE FROM LOCATIONS WHERE ID = ID;

DELETE FROM PEOPLE_LOGS WHERE ID = ID;
DELETE FROM LOCATIONS_LOGS WHERE ID = ID;
DELETE FROM PASSPORTS_LOGS WHERE ID = ID;

SELECT * FROM PEOPLE;
SELECT * FROM PEOPLE_LOGS;

SELECT * FROM LOCATIONS;
SELECT * FROM LOCATIONS_LOGS;

SELECT * FROM PASSPORTS;
SELECT * FROM PASSPORTS_LOGS;