CREATE OR REPLACE TRIGGER PEOPLE_UPDATE
    AFTER INSERT OR UPDATE OR DELETE
    ON PEOPLE
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO PEOPLE_LOGS VALUES (DEFAULT, 'INSERT', SYSTIMESTAMP, :NEW.ID, NULL, :NEW.NAME, NULL, :NEW.DATE_OF_BIRTH);
    ELSIF UPDATING THEN
        INSERT INTO PEOPLE_LOGS VALUES (DEFAULT, 'UPDATE', SYSTIMESTAMP, :OLD.ID, :OLD.NAME, :NEW.NAME, :OLD.DATE_OF_BIRTH, :NEW.DATE_OF_BIRTH);
    ELSE
        INSERT INTO PEOPLE_LOGS VALUES (DEFAULT, 'DELETE', SYSTIMESTAMP, :OLD.ID, :OLD.NAME, NULL, :OLD.DATE_OF_BIRTH, NULL);
    END IF;
END PEOPLE_UPDATE;

CREATE OR REPLACE TRIGGER LOCATIONS_UPDATE
    AFTER INSERT OR UPDATE OR DELETE
    ON LOCATIONS
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO LOCATIONS_LOGS VALUES (DEFAULT, 'INSERT', SYSTIMESTAMP, :NEW.ID, NULL, :NEW.ADDRESS, NULL, :NEW.POST_INDEX);
    ELSIF UPDATING THEN
        INSERT INTO LOCATIONS_LOGS VALUES (DEFAULT, 'UPDATE', SYSTIMESTAMP, :OLD.ID, :OLD.ADDRESS, :NEW.ADDRESS, :OLD.POST_INDEX, :NEW.POST_INDEX);
    ELSE
        INSERT INTO LOCATIONS_LOGS VALUES (DEFAULT, 'DELETE', SYSTIMESTAMP, :OLD.ID, :OLD.ADDRESS, NULL, :OLD.POST_INDEX, NULL);
    END IF;
END LOCATIONS_UPDATE;

CREATE OR REPLACE TRIGGER PASSPORTS_UPDATE
    AFTER INSERT OR UPDATE OR DELETE
    ON PASSPORTS
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO PASSPORTS_LOGS VALUES (DEFAULT, 'INSERT', SYSTIMESTAMP, :NEW.ID, NULL, :NEW.PERSON_ID, NULL, :NEW.ISSUE_DATE, NULL, :NEW.LOCATION_ID);
    ELSIF UPDATING THEN
        INSERT INTO PASSPORTS_LOGS VALUES (DEFAULT, 'UPDATE', SYSTIMESTAMP, :OLD.ID, :OLD.PERSON_ID, :NEW.PERSON_ID, :OLD.ISSUE_DATE, :NEW.ISSUE_DATE, :OLD.LOCATION_ID, :NEW.LOCATION_ID);
    ELSE
        INSERT INTO PASSPORTS_LOGS VALUES (DEFAULT, 'DELETE', SYSTIMESTAMP, :OLD.ID, :OLD.PERSON_ID, NULL, :OLD.ISSUE_DATE, NULL, :OLD.LOCATION_ID, NULL);
    END IF;
END PASSPORTS_UPDATE;
