CREATE OR REPLACE TRIGGER cascade_delete
    BEFORE DELETE ON GROUPS
    FOR EACH ROW
BEGIN
    BEGIN
        DELETE FROM STUDENTS WHERE GROUP_ID = :OLD.ID;
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
END cascade_delete;