-- INSERT INTO GROUPS(ID, NAME, C_VAL) VALUES (1, '123', 0);
-- INSERT INTO GROUPS(ID, NAME, C_VAL) VALUES (2, '231', 0);
-- INSERT INTO STUDENTS(NAME, GROUP_ID) VALUES ('A', 1);
-- INSERT INTO STUDENTS(NAME, GROUP_ID) VALUES ('B', 1);
-- INSERT INTO STUDENTS(NAME, GROUP_ID) VALUES ('C', 1);

DELETE FROM GROUPS WHERE ID = 1;
SELECT * FROM GROUPS FULL JOIN STUDENTS S on GROUPS.ID = S.GROUP_ID;
-- SELECT * FROM STUDENTS;
-- SELECT * FROM STUDENTS_LOGS
-- BEGIN
--     RESTORE(TO_TIMESTAMP('2023-02-24 14:57:00', 'yyyy-mm-dd hh24:mi:ss'));
-- end;
-- SELECT * FROM STUDENTS

-- select COUNT(*) from STUDENTS WHERE GROUP_ID = 1